name: CI
on:
    - push
    - workflow_dispatch

jobs:
    lint:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: npm ci
            - run: npx prettier -c .
